### ISSUE TITLE
Enum support

### ISSUE THREAD

**Issue by cem** [oatpp/oatpp-swagger#19]
Hi. Do you have any plans to support enum types?

**Comment by lganzzzo** [comment]
Hello @cem ,

Thanks for the question.

As I understand you are interested in adding `enum` with possible values for a parameter in swagger-UI.
This must be pretty easy to implement via the additional endpoint info

something like:

```cpp
ENDPOINT_INFO(getColor) {
  ...
  info->pathParams["color"].description = "Color name";
  info->pathParams["color"].enum = {"red", "green", "blue"};
}
ENDPOINT("GET", "/colors/{color}", getColor,
         PATH(String, color)) 
{
  mySelfWrittenColorParameterValidation(color); // manually implement color parameter validation.
  ...
}
```

As for the automatic validation of this parameter on the endpoint - it's something we need to investigate.

---

I'll add this to the scope - **implement enum field for parameter in EndpointInfo**

Regards,
Leonid

**Comment by lganzzzo** [comment]
Hello @cem ,

The support for `Enum` is already added in the latest `oatpp` and `oatpp-swagger`.

Please see the oatpp [changelog](https://github.com/oatpp/oatpp/blob/master/changelog/1.1.0.md#object-mapping-enum) for details.

```cpp
ENDPOINT("GET", "/colors/{color}", getColor,
         PATH(Enum<Color>, color))
{
  // No need to validate color values. All validations are already done.
  ...
}
```

Regards,
Leonid
