### ISSUE TITLE
DTO field description missing from "non-primitive" fields

### ISSUE THREAD

**Issue by yeefan** [oatpp/oatpp-swagger#29]
I am using Oat++ 1.1.0. Take the `example-crud` program, and modify the `UserDto` to become the following:
``` c++
class UserDto : public oatpp::DTO {
  
  DTO_INIT(UserDto, DTO)
  
  DTO_FIELD_INFO(id) {
    info->description = "ID";
  }
  DTO_FIELD(Int32, id);

  DTO_FIELD_INFO(firstName) {
    info->description = "First name";
  }
  DTO_FIELD(String, firstName, "first-name");

  DTO_FIELD_INFO(lastName) {
    info->description = "Last name";
  }
  DTO_FIELD(String, lastName, "last-name");

  DTO_FIELD_INFO(friends) {
    info->description = "Friends";
  }
  DTO_FIELD(Vector<String>, friends) = Vector<String>({});

  DTO_FIELD_INFO(enemies) {
    info->description = "Enemies";
  }
  DTO_FIELD(List<String>, enemies) = List<String>({});

  DTO_FIELD_INFO(subUser) {
    info->description = "Sub user";
  }
  DTO_FIELD(Object<UserDto>, subUser, "sub-user");

};
```
Compile the program and run it.
Go to the Swagger UI page and expand the schema for `UserDto`.
I could see the field descriptions for `id`, `first-name`, and `last-name`, which are "primitive" fields.
However, I cannot see the field descriptions for the `friends`, `enemies`, and `sub-user`, which are "non-primitive" fields containing a `Vector`, `List`, and another DTO respectively.
Is this a bug?
Thanks.

**Comment by lganzzzo** [comment]
Hey @yeefan ,

I've tested with your DTO, and I have descriptions (you just need to expand the item's details):
(Tested with the latest commits from `oatpp` and `oatpp-swagger`)

<img width="431" alt="Screenshot 2020-09-15 at 02 06 29" src="https://user-images.githubusercontent.com/5940640/93146703-32091600-f6f8-11ea-971b-26ff4b6e9149.png">

<img width="575" alt="Screenshot 2020-09-15 at 02 06 41" src="https://user-images.githubusercontent.com/5940640/93146715-3cc3ab00-f6f8-11ea-8bf3-27848e312f1d.png">

Please let me know if it still doesn't work for you.

Regards,
Leonid

**Comment by yeefan** [comment]
I'm sorry, I should have checked the master branch before filing this issue. Let me look at the master branch later.
(Descriptions for "non-primitive" fields certainly aren't there in the 1.1.0 release.)

**Comment by lganzzzo** [comment]
No problem.
You are right, these improvements were added after the 1.1.0 release

**Comment by lganzzzo** [comment]
Closing the issue...
