### ISSUE TITLE
Inherited fields not visible in schema documentation

### ISSUE THREAD

**Issue by sholmp** [oatpp/oatpp-swagger#37]
When a DTO inherits from a parent DTO, the inherited fields are not visible in the generated swagger schema documentation. Is this intentional?

**Comment by lganzzzo** [comment]
Hey @sholmp ,

Please post your `DTO` declaration code.

I assume you just missed to inherit fields.

```cpp
class MyChildDto : public MyParentDto {
 
  DTO_INIT(MyChildDto, MyParentDto /* Extends */) //<---- Don't miss this

}
```

**Comment by sholmp** [comment]
Yep you are right. I did exactly what you mentioned inherited but did not DTO_INIT correctly... :smile:

**Comment by lganzzzo** [comment]
:) Ok, closing this issue then
