### ISSUE TITLE
Is reverse conversion possible?

### ISSUE THREAD

**Issue by lewiswilliam** [oatpp/oatpp-swagger#41]
Hi
We have a bunch of swagger specifications and need to generate oatpp/oatpp-swagger code for the same. Is this possible to do in any way?
Any pointers will be appreaciated.
Regards
William

**Comment by lganzzzo** [comment]
Hello @lewiswilliam ,

This feature is scheduled for the `1.3.0` release.
https://github.com/oatpp/oatpp/issues/331

At the moment it's not implemented.

**Comment by lewiswilliam** [comment]
Hello @lganzzzo 

Appreciate your response. Thank you.

Regards
William
