### ISSUE TITLE
SWAGGER_ROOT_PATH defines missing in cmake-module

### ISSUE THREAD

**Issue by bamkrs** [oatpp/oatpp-swagger#61]
As first found in https://github.com/oatpp/example-crud/issues/22 the new variables introduced in https://github.com/oatpp/oatpp-swagger/commit/652f95c6fbc31d8bc17f94fd7820fba01399e8ec are not applied to the modules cmake file and thus not set for other projects.

**Comment by lganzzzo** [comment]
Fixed in https://github.com/oatpp/oatpp-swagger/pull/70
