### ISSUE TITLE
Content-Type not set for CSS or JS responses

### ISSUE THREAD

**Issue by oglimmer** [oatpp/oatpp-swagger#69]
**ISSUE:**

http responses to any **.css or **.js files do not set the http header "Content-Type".

This is not correct and this gets a real issue when running behind proxy server which sets a default content type if none is set.

**HOW TO REPRODUCE**

* Start https://github.com/oatpp/example-crud
* curl "http://localhost:8000/swagger/swagger-ui.css" -v -o /dev/null -s
* There is no Content-Type

**FIX**

ok this is not a real fix, thus I haven't created a PR, but it gives an idea what could fix the problem:

https://github.com/oglimmer/oatpp-swagger/commit/159bf26bcf1d24cf00f25c3541c3fc6c3b541cc1

**Comment by lganzzzo** [comment]
Hello @oglimmer ,

Thanks for the issue!

> ok this is not a real fix, thus I haven't created a PR, but it gives an idea what could fix the problem:

This looks good enough for swagger resources. 
Please add the same for `AsyncController` and please send your PR!

Regards,
Leonid

**Comment by oglimmer** [comment]
Sent PR, see https://github.com/oatpp/oatpp-swagger/pull/71
